### ISSUE TITLE
很多作業問題

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp3-discussion#10]
1. 請問boss可以覆寫mine.bin嗎？可以建立題目中未要求的檔案嗎？
2. config.txt中的MINE、MINER的檔名可否包含”\~”(home directory)？因為C/C++的檔案讀寫函數似乎都不支援~到home directory的轉換，會造成”\~”無法識別的錯誤
3. 關於dump的問題：據我所知，mine通常不會很大(<100kb)，因此很難會有要寫入的資料造成blocking的問題吧？然後spec中有提示可以用select避免blocking，但是根據我對select的了解，還是不太清楚怎麼用select避免blocking，檔案總得要全部寫入吧？難道是切成每塊100kb分塊寫入檔案，然後記住寫到哪裡了，return回去迴圈看看有沒有其他輸入，然後再想辦法自動回來（第一次是因為stdin觸發的，第二次以後就得想辦法特判……）看看100kb寫完了沒、還有沒有要寫的，再return回去……這樣也太麻煩了吧？而且又規定不能multi-threading，又有可能user要求寫到其他檔案，因此有可能有超多個檔案處於「正在寫入」的狀態，還要自己在single thread的狀態下手刻multiplexing切來切去……怎麼想這樣的要求未免也太不合理，求解？
4. miner算10000次hash才理boss一次是合法的嗎（延遲在0.5秒內）？會不會影響到status的評分（因為當miner在算第5000個hash的時候傳送status訊號，得到的會是第10000個hash）？
5. 承4.，quit呢？總之當user輸入input到stdin時，boss要在多少時間內做出回應？當boss要miner做甚麼事的時候，miner要在多少時間內做出回應？當miner要通知boos某件事，boss要在多少時間內做出回應？
6. 當同時有兩個miner挖到礦了，說I found a treasure，然後通知boss，這時boss要怎麼應對？我目前的作法是2個treasure都接收，print出2次「A treasure found」，但只對找到第1個treasure的miner做出之後的回應，諸如reassign jobs、叫其他miner（包含找到第2個treasure的miner）print *** found a treasure等等。這樣OK嗎？

**Comment by jerry73204** [comment]
1. (1) dump的時候如果檔案存在，請直接覆寫。(2)不影響評測的前提可以自由創建檔案。
2. ~是shell的語法糖，設定檔路徑不會含~。
3. 我會將你程式dump到一個named pipe才測試是否有實作多工，這是作業要求。
4. 只要沒有明顯有感的延遲就可以（延遲儘量不要超過5秒）。
5. 同4.。
6. 只要完成挖到一次寶後，其他就要廣播訊息的功能就可以，作業沒有其他規定。

**Comment by jerry73204** [comment]
上面第2點～變成刪除現了，補充一下
* 設定檔不會有～
* quit指令之後不再接收新指令，等到所有寫入工作完成後結束程式
