### ISSUE TITLE
視窗分割的問題

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp3-discussion#11]
這邊還想請問一個很菜的問題，助教在上禮拜五晚上demo pipe的時候，同時打開了兩個視窗方便檢查，想要請問如何打開兩個分離，可以同時檢視的視窗呢，我目前只有查到使用screen指令可以執行多個terminal，但還是需要使用 screen -r 指令一次檢查一個視窗，有一點不方便，想要請問助教相關的指令或是關鍵字，謝謝！

**Comment by jerry73204** [comment]
screen有分割視窗功能
http://aperiodic.net/screen/quick_reference#split_screen

如果你用Ubuntu，Ctrl+T開新終端機，ALT+tab切換市場，Windows鍵+上/左/右 自動排版視窗。
