### ISSUE TITLE
關於dump的蠢問題

### ISSUE THREAD

**Issue by singyaowu** [SystemProgrammingatNTU/mp3-discussion#13]
抱歉我程度不好問個蠢問題。我看完dump的敘述後還是有點搞不太懂為什麼會用到select？我不能直接把檔案設成nonblocking直接write後就不理它嗎？這樣會出現什麼錯嗎？

**Comment by jerry73204** [comment]
為了必須能同時寫檔和讀取指令，用select同時檢查read set和write set可以達到多工的效果。

評測標準是要求完成multiple IO，無論你使用select和非阻塞IO都可以。

**Comment by singyaowu** [comment]
可是如果我直接設成nonblocking後write，不是會一次全部寫進kernal嗎？這樣我不太清楚select何時會用到。網路上找到的select好像都是read比較多，助教能提供write跟select的例子嗎？
如果我先把write設為nonblocking後，write()之後select，select說我寫完了，那跟我設nonblocking後write()之後就不理他有什麼差別阿？

**Comment by jerry73204** [comment]
> 可是如果我直接設成nonblocking後write，不是會一次全部寫進kernel嗎

這不見得，舉例來說，如果寫入的對象是pipe或者socket，寫入頂多到kernel buffer塞滿。使用`select()`或者非阻塞IO可能會發生一種情形，當得知fd可以寫入時，執行`write()`至少寫入1個byte，但是不一定全部寫完。
```c
ssize_t size_written = write(fd, buf, buf_size); // size_written < buf_size is possible
```

在使用阻塞IO的情況下，使用`select()`的好處是你可以得知fd何時可以寫入，確保你接下來執行`write()`不會被阻塞。當然，非阻塞IO是另一種解決方式，但是實作時得注意busy-waiting問題。

作業要求執行dump指令後，對於後續使用者輸入還是要responsive，理由是不希望程式可能因執行很大量的寫入而阻塞其他的工作。評測時候我會將程式dump輸出到一個pipe來檢驗。

**Comment by singyaowu** [comment]
哦哦 感謝助教 我好像有點懂了
