### ISSUE TITLE
請問程式執行中mine.bin可以被修改嗎?以及reuse問題

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp3-discussion#15]
請問一下程式執行中mine.bin是可以去修改mine.bin的嗎?
例如挖到寶就把當下append的結果覆寫到mine.bin裡
如果不行的話，那麼下次reuse時如果又是挖同一個mine.bin，會變成重挖的效果嗎？(上次挖到4字寶，但這次還是從學號開始挖)
如果可以的話，那麼下次reuse時如果又是挖mine.bin，會變成延續上次繼續挖的效果
請問是哪一種呢?或是測資的config file根本不會兩次挖同一個MINE?
感謝助教回答

**Comment by jerry73204** [comment]
作業沒規定能不能修改檔，這點可以自由發揮。
只要完成
1.程式開始時從設定檔指定的mine.bin開始計算
2.正確實作dump功能
