### ISSUE TITLE
STATUS

### ISSUE THREAD

**Issue by plsmaop** [SystemProgrammingatNTU/mp3-discussion#18]
如果收到status指令時，treasure 是0要輸出什麼？

best 0-treasure in 0 bytes\n

這樣嗎？

**Comment by jerry73204** [comment]
是的，請省略雜湊值。
抱歉這點我待會補充到作業spec裏面。

**Comment by s123unny** [comment]
in X bytes 不用包含學號的長度嗎?

**Comment by jerry73204** [comment]
需要，byte數目也等同dump出來的檔案大小。

**Comment by s123unny** [comment]
所以當甚麼都還沒找到的時候，應該是
    best 0-treasure in 9 bytes\n
這樣嗎??
另外，可以不省略雜湊值嗎QQ
就直接照本來的格式輸出沒有零的hash(?

**Comment by jerry73204** [comment]
已經補充沒有找到n-treasure的輸出在spec上了，請輸出
```
best 0-treasure in 0 bytes\n
```

**Comment by fsps60312** [comment]
所以判斷要寫成：
如果是0-treasure，當作0 bytes
否則就是實際的bytes
這樣嗎？

**Comment by jerry73204** [comment]
是的。
