### ISSUE TITLE
pipe_ptr->input_pipe/output_pipe?

### ISSUE THREAD

**Issue by s123unny** [SystemProgrammingatNTU/mp3-discussion#2]
boss.c:71:
fd_ptr->output_fd = open(pipe_ptr->input_pipe, O_RDONLY);
client.c:33:
int output_fd = open(input_pipe, O_WRONLY);
這兩行的input_pipe是不是應該改成output_pipe?

**Comment by jerry73204** [comment]
謝謝指正，馬上修正。
