### ISSUE TITLE
作業的幾個問題

### ISSUE THREAD

**Issue by sea120424** [SystemProgrammingatNTU/mp3-discussion#20]
抱歉，我的英文不太好，想確認幾個問題
1. config.txt 的第一行是MINE，她只會用來交代初始的字，之後都不會更動檔案嗎？

2. dump的內容是 string 還是 MD5

3. 如果挖3-寶時挖到前4個是0的，可以把它當3-寶用嗎？

**Comment by jerry73204** [comment]
1. MINE是程式開始計算的起始點，之後dump出來的結果的前綴必須包含MINE檔案的資料。作業沒規定能不能更動檔案。
2. binary data，不是MD5
3. 不能，作業規格有強調三寶必須有exactly三個零
