### ISSUE TITLE
關於DUMP的問題

### ISSUE THREAD

**Issue by 0970jyjytwtw** [SystemProgrammingatNTU/mp3-discussion#21]
(1)請問有可能短時間連續出現兩個dump的指令嗎?
(2)有可能短時間內兩次dump到同一個路徑嗎? 如果會的話，那因為dump不能block住，所以第一個dump寫到一半，發現有第二個dump，再切到第二個dump寫，第二個dump寫完，再回去第一個DUMP寫，這樣第一個dump就會覆寫到第二個DUMP寫的東西了吧? 那這樣要怎麼辦?

**Comment by jerry73204** [comment]
1. 是的
2. 只要保證程式quit之後，dump出來的資料是最後一次的就行，沒規定實作方式。
