### ISSUE TITLE
name_pipe open for read and write

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp3-discussion#23]
想要請問一下助教 我的程式原本把pipe分別開 RD_ONLY WR_ONLY時，確認了好幾次流程都檢查不出問題，每個read都對應到一個write，但是一直有很多無法得知的問題發生。在現在這個測試階段，我讓server端找到一個寶礦就離開迴圈，但是找到寶礦的miner印了找到的訊息就直接離開迴圈，儘管我沒有輸入任何從迴圈break的指令。另一方面，沒找到寶礦的卻一直印一樣的訊息（我的server已經結束，應該沒有傳訊息到pipe，但是miner卻一直好像讀到一樣的訊息，無限的印下去)。奇怪的是，印的東西還不是每一次都一樣。結果很意外的，把所有的pipe open for RDWR，bug就消失了 找到寶礦的miner印了找到的訊息後沒有結束程序，其他的也只接收到一次訊息，一切都如作業要求的進行。想要問問助教這是什麼狀況，還是我可能漏考慮了什麼，謝謝！不知道會不會跟我使用screen開視窗有關，因為我真的想很久都想不出為什麼...

**Comment by jerry73204** [comment]
> 會不會跟我使用screen開視窗有關

助教用過幾年的Linux還沒碰過這種情況。

如果程式的執行方式不符合設想的流程，通常是這兩種情況
1. 邏輯失誤
2. 發生記憶體污染，變數被覆寫成其他的值而改變程式流程

爲了避免記憶體污染，檢查看看有沒有這些常見錯誤
1. hard-coded size，請用sizeof或者變數替代
```c
char buf[1024];
ssize_t sz = read(fd, buf, 4096); //忘記改
```
2. sizeof pointer，這會算出pointer本身的大小
```c
char *str = "some loooooong string";
printf("%d\n", sizeof(str)); // 大部分電腦是得到常數8
```
3. malloc長度計算失誤
```c
/* 建立1000個整數的陣列 */
int *array = (int*) malloc(1000); // 算錯了，應該寫sizeof(int) * 1000
array[999] = 123; // 這兒超出陣列範圍，但是編譯會過
```
4. off-by-one error
```c
char str[] = "original string";
char *new_str = malloc(sizeof(char) * strlen(str)); // 注意這裏strlen沒有把\0字算進去
strcpy(new_str, str); // strcpy()to在new_str多寫一個\0，超出malloc()的範圍
```

如果上述還是沒有辦法解決問題，強烈推薦使用gdb除錯神器。

**Comment by plsmaop** [comment]
請問如果用O_RDWR會被扣分嗎？

**Comment by jerry73204** [comment]
這部分請依照作業規定，使用O_RDONLY或O_WRONLY。
根據POSIX的規範fifo不一定是雙向，而且kernel對於每個fifo只會維護一個buffer（見`pipe(7)`），如果你使用O_RDWR，可能會有一種情況是程式同時這個fifo的reader和writer，你可以寫個小程式驗證看看。也建議不要冒着程式有不預期行爲的風險。
