### ISSUE TITLE
NAMED PIPE 的問題

### ISSUE THREAD

**Issue by 0970jyjytwtw** [SystemProgrammingatNTU/mp3-discussion#24]
我在工作站上寫了一個程式，他會先open一個named pipe，然後一直slect那個named pipe，如果可以讀就讀他，並且輸出read的回傳值。我開著這個程式，並在另一個TERMINAL用echo來輸入那個named pipe，結果當echo已經結束了，slect居然都一直說named pipe現在可以讀，而且read的回傳值都是0，這是為什麼?

**Comment by jerry73204** [comment]
當writer對named pipe執行close()之後，reader的read()永遠會得到0回傳值。套用你的情況是在shell執行echo之後就會close那個named pipe。因此，若你的client想重用那個named pipe，必須也跟着close再重新open一次。
