### ISSUE TITLE
關於blocking read write

### ISSUE THREAD

**Issue by b03201003** [SystemProgrammingatNTU/mp3-discussion#25]
助教您好
目前打算讓read write都能夠block住
希望write幾次就對應到read幾次 

至於如果想要做到read write一一對應的話
是否一定要去控制好相對應的read write要求相同長度呢
例如這端write一個byte 另一端就要剛好read一個byte這樣(這樣還需要兩邊溝通訊息長度頗麻煩QAQ)

或是有什麼更好的思路或是實作方法嗎
謝謝

**Comment by jerry73204** [comment]
大哥沒三行哦。

**Comment by b03201003** [comment]
啊 忘了打問題就送出...

**Comment by b03201003** [comment]
另外 如果要使read write都block住需要另外設定什麼嗎
目前單純把input output的fifo直接open
但是在miner端的while read沒有停住QAQ

**Comment by jerry73204** [comment]
> 目前打算讓read write都能夠block住
> 希望write幾次就對應到read幾次
>  至於如果想要做到read write一一對應的話
> 是否一定要去控制好相對應的read write要求相同長度呢

寫入和讀取不超過pipe buffer size，這點的確不難做到，但是肯定有幾個例外，一是你無法控制kernel開多大的pipe buffer，也無法知道對方是否已經讀取乾淨，二是有可能`write()`或`read()`中途程式吃到signal，導致資料不完全寫入或讀出。甚至若操作對象是使用者（比如終端機），上面的方法顯然不適用。

資料寫入或讀出不完整，檢查`read()`或`write()`回傳值隨時可以重做，但是server無法預期client何時送資料的情況下，可能會單方面阻塞，你可以考慮使用multiplexing或者非阻塞IO處理。
