### ISSUE TITLE
Dump可以卡住server和client之間的溝通嗎

### ISSUE THREAD

**Issue by 0970jyjytwtw** [SystemProgrammingatNTU/mp3-discussion#28]
如題，助教會一開始就直接dump到named pipe，然後卡三十分鐘嗎？

**Comment by jerry73204** [comment]
不會那麼長，基本上是五分鐘。

**Comment by jerry73204** [comment]
看標題是不是有誤會，dump到的FIFO和client生出來的pipe沒有關係。

**Comment by 0970jyjytwtw** [comment]
我的意思是，DUMP的時候，SERVER如果沒有任何STDIN，是不是就可以放心持續把treasure write進那個檔案裡，直到完成，也就是DUMP的時候只有select STDIN而已?

**Comment by jerry73204** [comment]
可以，只要在程式結束前完成所有寫入工作。
