### ISSUE TITLE
關於quit

### ISSUE THREAD

**Issue by b05902109** [SystemProgrammingatNTU/mp3-discussion#29]
quit後的reuse
是從0-寶開始挖 還是從上一個最佳n-寶開始挖?

**Comment by jerry73204** [comment]
從mine.bin找到最好的n寶開始算。

**Comment by ghost** [comment]
如果mine.bin一開始算出來就有n個0
也是從n寶開始算嗎？

- - - -

抱歉
我有點搞混了
"從mine.bin找到最好的n寶開始算。"的意思是
server需要去更新mine.bin的內容然後下次從上次算出來的繼續
還是server開始的時候要去問client上次算到哪裡了再開始分配工作？

**Comment by jerry73204** [comment]
server開啟時會讀取設定檔寫的mine.bin，假設mine.bin最好已經包含到3寶，server就從mine.bin的內容繼續往後加東西尋找4寶，以此類推。沒有強制要存回mine.bin。
client只會做server要求的工作。

**Comment by ghost** [comment]
意思是開始之前一定要先把mine.bin有幾寶算出來嗎？
這個部分可以在server算嗎？

**Comment by jerry73204** [comment]
> 意思是開始之前一定要先把mine.bin有幾寶算出來嗎？

是，規格提到`MINE: A file storing the binary string, the mine. The server will try to append some bytes to it to find out treasures.`

> 這個部分可以在server算嗎？

請想看看。

**Comment by ghost** [comment]
> 請想想看。
助教好，
我想了一下覺得應該在哪一邊都算得出來（？
還是有規定server一開始不能block住嗎？

**Comment by jerry73204** [comment]
server必須能隨時接受使用者輸入。

**Comment by ghost** [comment]
那讀檔讀到一半收到dump 
跟dump到一半收到quit的時候要怎麼處理？

**Comment by ghost** [comment]
另外client在算很大的md5的時候可以block住嗎？
還是也要隨時能回應status和quit?

**Comment by jerry73204** [comment]
> 那讀檔讀到一半收到dump

如果讀檔真的很花時間，請直接輸出空擋。助教不會測試這部分。

> 跟dump到一半收到quit的時候要怎麼處理？

quit之後請等待所有IO工作結束後結束程式，中途不再處理任何新使用者指令。

**Comment by ghost** [comment]
助教好，剛剛還有多問一個問題
好像沒回答到><

> 另外client在算很大的md5的時候可以block住嗎？
> 還是也要隨時能回應status和quit?

**Comment by jerry73204** [comment]
確保server總是對輸入指令總是responsive即可。

**Comment by hengzhichin** [comment]
助教你好，看了回應有提到

> 「server開啟時會讀取設定檔寫的mine.bin，**假設mine.bin最好已經包含到3寶**，server就從mine.bin的內容繼續往後加東西尋找4寶，以此類推。」

請問這是發生在 只有reused的情況嗎？還是任何情況？

之前在別篇回應有看到 不能跳過treasure 是指什麼？

試著理解如下，

指不管任何情況 ， 都從當前mine.bin 最好的treasure 往後「依序」加，

如  最開始讀入 就有 4寶  就往後 5寶 6寶 找下去， 

而另一篇回應提到的是，不能在4寶的時候 ，發現6寶，就不找5寶

-----

總之就是，「依序找」，但一開始不一定是從1寶開始找，

不知道我有理解錯誤嗎

謝謝助教

**Comment by jerry73204** [comment]
理解正確。
你可以想成dump就是存檔，server開啟時讀取mine.bin是載入存檔。
只是這裡的mine.bin內容不一定剛好是n寶，也有可能是其內容的前綴包含n寶。

**Comment by ghost** [comment]
> 只是這裡的mine.bin內容不一定剛好是n寶，也有可能是其內容的前綴包含n寶。

這裡前綴可能包含n寶的意思是
開啟mine.bin的時候要一個字一個字檢查嗎？
這個n寶的前綴裡要有1...n-1寶嗎
還是有n個0就行

**Comment by jerry73204** [comment]
> 這個n寶的前綴裡要有1...n-1寶嗎

根據spec定義沒錯。

**Comment by hengzhichin** [comment]
我好像有點搞混了XD

> 只是這裡的mine.bin內容**不一定剛好是n寶**，也有可能**是其內容的前綴包含n寶**。

----

我想到幾種情況，不好意思再麻煩助教了

1. 首次開啟，
假設mine.bin 儲存的是學號 （假設學號未有任何寶，且前綴也沒有任何寶）， 沒問題append尋找1寶

2. 首次開啟，
假設mine.bin 儲存的是學號 （假設學號未有任何寶，但前綴有2寶,1寶）， 這時候是否要從3寶找？

3. 首次開啟，
假設mine.bin是助教自己生的dump檔，
根據dump定義 The server writes the best n-treasure to this file
因此，目前檔案已經是n寶，所以我要開始往回，從前綴找出 n-1,....1寶？




4. reused階段，
假設 boss 先 dump 到路徑/tmp/dump1
這時候quit，然後修改config 的
MINE: /tmp/dump1
boss再開啟，因此會發現目前有n寶，開始尋找前綴內容的，n-1....1寶
（這個目前應該是確定這樣做了）

5. reused階段，
假設 boss 先 dump 到路徑/tmp/dump2
這時候quit，然後修改config 的MINE: /tmp/XYZ 非 /tmp/dump2 
且**XYZ也非存檔**
boss再開啟，是否要當存檔？
（這情況是reused階段，mine卻指向一個新檔案，而非存檔）


整理一下，想問的就是，
1. reused階段，是否一定是reused dump存檔？如果非dump檔，要怎麼處理？例如說，突然想要resued到別的新學號？如，原本算B123，dump到某處，不再算他，然後reused拿來算“B999”

2. 首次階段是否要當可能是存檔看？或是，首次階段，是否要檢查前綴是否已經存在寶？

**Comment by jerry73204** [comment]
請注意題目設定：即使雜湊值有n個0，前面必須包含n-1寶才能算是n寶。因此
1沒錯
2沒錯
3請根據定義檢查是不是真的n寶，dump出來的結果就是最佳進度
4同3說明
5server開啟時不用管之前的伺服做了什麼事，直接從指定的檔案開始算即可。

總而言之，伺服器載入MINE欄位的檔案總是要先檢查它到幾個寶，就會知道計算上的最佳進度，無關於前面的server做過什麼事情。

**Comment by ghost** [comment]
> 請根據定義檢查是不是真的n寶，dump出來的結果就是最佳進度

請問一開始是0寶的話
最佳進度是整個mine_file還是空字串？

**Comment by jerry73204** [comment]
dump出來是空檔，不過計算的進度請從mine.bin尾巴開始。

**Comment by drevil5678** [comment]
如果mine本來是5-treasure
可以直接把他當作是0-treasure往下append找寶嗎?

**Comment by jerry73204** [comment]
> 如果mine本來是5-treasure
> 可以直接把他當作是0-treasure往下append找寶嗎?

"理論上"是不違反規則

**Comment by timlee0119** [comment]
助教您好，借版再請問一下，作業要求裡面有說到只要在30分鐘內找到3寶就好，那如果你測資給的mine.bin一開始就是超過三寶，是不是就代表其實也可以不用繼續找了，因為按照定義我已經找到3寶了？
感謝助教回答

**Comment by jerry73204** [comment]
非討論串相關請另外發文。
