### ISSUE TITLE
Spec相關問題

### ISSUE THREAD

**Issue by tsunghan-wu** [SystemProgrammingatNTU/mp3-discussion#3]
助教請問兩個問題：
1. 檔名長度的限制為何？(Mine跟Miner)
2. 可以自己開一個include的資料夾自己寫protocol的struct嗎？因為spec有寫道裡面只會有兩個資料夾

**Comment by jerry73204** [comment]
1. 長度不超過PATH_MAX
2. 只要不影響助教評測，基本上可以自由設置檔案或目錄
