### ISSUE TITLE
問題

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp3-discussion#31]
如果mine.bin有1GB的話，算一次md5不是就要很久嗎（更何況判斷n-treasure的n是多少）？而且boss還要把工作丟給miner、miner還要把treasure丟回給boss耶，這樣的來來回回每次都要1G會不會太不實際？
然後server要存檔、讀檔都會很痛苦><

**Comment by jerry73204** [comment]
評分不會以1G為基準來檢測能不能算出三寶，做到功能上實現可以處理大資料就可以。

挖礦的時候可以不需要每次重新複製1G的資料，你可以想看看怎麼做。

最後，這位帳號可否整理出所有問題一次發文，到處點連接很累逆。

**Comment by fsps60312** [comment]
那如果無法處理大檔案會被扣幾分呢？
我的dump有實作multiple I/O（fifo不會發生block），但mine.bin有1G的話會爆掉QQ

**Comment by fsps60312** [comment]
如果要改成可處理1G的mine.bin又不能用超過2G記憶體的話我可能整個protocol、架構、邏輯判斷、不管boss還是miner都要重寫了......助教求饒啊......QQ

**Comment by jerry73204** [comment]
可以使用length extension attack技巧大量節省記憶體。
```c
const char* data = "B05902xxx...";
MD5_CTX context;
MD5_CTX working_context;
// init, update, do stuffs ...
memcpy(&working_context, &context, sizeof(MD5_CTX));
```
加油囉。

**Comment by timlee0119** [comment]
借版問一下，mine.bin裡面存的不就是我們的學號嗎? 那怎麼還會有檔案很大的問題呢？不太了解意思，感謝助教回答

**Comment by jerry73204** [comment]
那是規格的範例，規格前文有說明`A mine is an arbitrary binary string. `、`Let’s start with your student ID in upper case as your mine`。

mine.bin儲存*mine*，可以是任意長字串，當然不一定是你的學號。
