### ISSUE TITLE
config.txt 的格式

### ISSUE THREAD

**Issue by sea120424** [SystemProgrammingatNTU/mp3-discussion#32]
config.txt最後一行
MINER: /tmp/margaret_in /tmp/margaret_out\n
MINER: /tmp/hopper_in /tmp/hopper_out\n
EOF\n
要直接寫EOF三個字嗎？還是只是代表檔案結束，那最後的換行符號要加嗎

**Comment by ghost** [comment]
那個EOF應該只是shell語法？

**Comment by jerry73204** [comment]
EOF不是檔案內容，是shell上稱爲heredoc的語法，允許你直接在shell指令輸入多行的內容後標記內容結束。

```sh
# <<表示以下內容當做stdin資料，並使用EOF作爲內容終止符
cat > config.txt <<EOF
your line.
your document.
your bbbbllllllaaaaa.
EOF # 表示內容結束
```
