### ISSUE TITLE
關於fd_set裡面的內容

### ISSUE THREAD

**Issue by b03201003** [SystemProgrammingatNTU/mp3-discussion#33]
因為不知為何好像程式透過FD_ISSET的判斷好像出了很多誤判
想檢查看看readset writeset裡面是否有正確輸入
請問該如何做呢
查了一些資料仍不太明白
謝謝!

**Comment by jerry73204** [comment]
是不是把宣告的fd_set多次`select()`，而沒有重新初始化？
