### ISSUE TITLE
named pipe reuse

### ISSUE THREAD

**Issue by jd3main** [SystemProgrammingatNTU/mp3-discussion#36]
請問會有已經存在同樣名稱的 named pipe 的情況嗎?
照助教給的 code 會直接被 assert 結束
我們需要在 miner 終止前刪除那個 named pipe 嗎?
又或者是要先嘗試刪除再 mkfifo

**Comment by jd3main** [comment]
順便問一下
"Multi-threading is not allowed"
是只計算不能用 還是也不能用 fork 來 dump

**Comment by jerry73204** [comment]
> 請問會有已經存在同樣名稱的 named pipe 的情況嗎?

不會

> 我們需要在 miner 終止前刪除那個 named pipe 嗎?

作業沒規定，要怎麼做都行。
