### ISSUE TITLE
記憶體用量問題

### ISSUE THREAD

**Issue by tsunghan-wu** [SystemProgrammingatNTU/mp3-discussion#37]
請問助教
請問我現在要檢測記憶體用量(2G)
有什麼比較好的方式嗎？
因為我目前想到的就是 `$ps-ux` comand
只不過我不清楚的是2G是VSZ+RSS嗎？
還是只有其中一項？

**Comment by jerry73204** [comment]
可以使用ulimit。

**Comment by jerry73204** [comment]
ulimit限制virtual memory，請參考VSZ欄位。

**Comment by tsunghan-wu** [comment]
了解，謝謝助教
