### ISSUE TITLE
請求作業延期

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp3-discussion#39]
昨天晚上才知道mine.bin可以到1G這個規定，之前N天N夜終於以為寫完的作業全部都白費了，今天還有線性代數期中考要準備，MP3死線又在今晚，早八打完羽球也累了，真的不知道早早寫完作業有甚麼好處。這樣下去寫不完啦，請求作業再延一個禮拜，求求你，這樣真的太狠了QQ<(_ _)>（而且接下來我要出國比賽，再延一個禮拜也不知道夠不夠！！！）
強烈建議下次給大家local judge來本地測，不然根本很難猜到dump檔案大到會block是甚麼狀況......然後沒有強調的限制也很難抓到平衡點，有些限制是相斥的，例如檔案大小、記憶體限制、執行時間、反應時間，就算是很厲害的人也很難顧全啊。下次給我們local judge讓我們知道你們要考我們甚麼好不好？

**Comment by duck105** [comment]
推QQQ

**Comment by fsps60312** [comment]
然後挖礦比賽......身為帳號管理組，覺得工作站不能這樣操（其實我們整組意見幾乎一致），找到夠多0就好，這樣沒限制的要大家去占用工作站資源，就只是為了暴搜再多賽到一個0，對誰都不公平啊......而且工作站滿載，甚至會害其他還沒寫完作業的同學使用工作站出現困難（更何況除了SP以外還有其他很多課程的作業也需要使用到工作站資源啊！），這樣應該不太合理吧？***強烈建議停止比賽***，還給大家一個乾淨快速的工作站，雖然我現在是第二名，但我自願放棄那2分，也不要讓這場比賽害其他原本有能力的同學拿不到基本分！

**Comment by leo08260826** [comment]
推推

**Comment by b05902085-felixthecat** [comment]
推推

**Comment by 0970jyjytwtw** [comment]
推推

**Comment by chishengshih** [comment]
我們跟助教討論一下。

**Comment by b03201003** [comment]
延期+1QAQ
還有好多科作業在追殺人

**Comment by drevil5678** [comment]
推推推推推

**Comment by peter9503** [comment]
push

**Comment by a127000555** [comment]
push><

**Comment by chishengshih** [comment]
會延後繳交的期間，競賽的規則也會修改。助教等一下公布詳細內容。

**Comment by jerry73204** [comment]
死線改時到12/10日23:59分，遲交死線改時到12/13日23:59分。

我們也修改競賽辦法了，死線前上傳五寶可以得到共1分加分，七寶可以得到額外共2分。
