### ISSUE TITLE
判斷n寶

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp3-discussion#43]
一開始要判斷1G的mine.bin是幾n寶，如果每用MD5Update append一個byte就MD5Final一次看前面幾個0是不是效能會太慘？經測試要花費1分多鐘......這樣可以嗎？還是有其他方法？
這段時間應該不用理會user輸入的指令吧？畢竟初始資料都還沒分析完

**Comment by jerry73204** [comment]
1分鐘已經足夠了，評測標準是30分鐘。
使用者指令必須總是responsive，這個是作業要求，可以想看看怎麼處理。
