### ISSUE TITLE
無法上傳md5 rush

### ISSUE THREAD

**Issue by ghost** [SystemProgrammingatNTU/mp3-discussion#44]
助教好
我上傳的時候一直出現
`檔案格式不正確，請確認內容以大寫學號開頭，且最終MD5雜湊值有最佳數個n零開頭`
檔案如附件：
[8.txt](https://github.com/SystemProgrammingatNTU/mp3-discussion/files/1531052/8.txt)

**Comment by fsps60312** [comment]
n寶要以某n-1寶為prefix，不用在後面加上'\n'
然後我不是助教(?)

**Comment by ghost** [comment]
我發現ㄌ我的沒有包含一寶QQ
