### ISSUE TITLE
Dump測試

### ISSUE THREAD

**Issue by plsmaop** [SystemProgrammingatNTU/mp3-discussion#45]
不好意思請問助教可以提供一些測試dump多工的方法嗎QQ

我用別的程式開name pipe來測試dump，但一旦開啟fifo，server就馬上select到了，有什麼辦法能卡住server讓他select不到啊

**Comment by jerry73204** [comment]
> 有什麼辦法能卡住server讓他select不到啊

你很難改變`select()`行爲，有比這更好的測試方式，寫個程式開檔不讀就可以了。

```sh
mkfifo fifo
exec 3< fifo # open file
exec 3<&-   # close file
```
