### ISSUE TITLE
同時dump到多份檔案

### ISSUE THREAD

**Issue by b05902053** [SystemProgrammingatNTU/mp3-discussion#47]
1. dump 檔名
是否保證檔名是個regular file
應該不會dump到一個fifo去吧

2. 有三個 regualr file A, B, C
如果打
dump A
dump B
dump C
quit
A 還沒寫完時 就在stdin收到dump B
然後B還沒寫完時就接到dump C
最後C還沒寫完就quit
(1) 那A, B, C dump出來的內容是要以接到指令當下時的內容為準嗎?
例如
打dump A的時候是1寶 B的時候到4寶 C的時候6寶
A, B, C在程式結束後的內容是不是就是
1寶, 4寶, 6寶?
(2) 先把A寫完再去寫B 還是先把B寫完再寫A
是不是都可以?

**Comment by jerry73204** [comment]
1. 有可能是FIFO
2. 沒規定，只要quit結束程式之後，其雜湊曾經在終端出現過即可

**Comment by b05902053** [comment]
那如果dump到FIFO
server對FIFO
write的時候
助教會幫我們read嗎?
如果我們自己開一個read和一個write
這樣dump完FIFO大小還是0 byte的樣子

不知道dump到FIFO有什麼要求?

**Comment by jerry73204** [comment]
> 這樣dump完FIFO大小還是0 byte的樣子

請看man fifo

> 助教會幫我們read嗎?

不一定，細節請看舊推文。
