### ISSUE TITLE
作業要求: 找到3寶細節問題

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp3-discussion#48]
助教您好，想請問一下，作業要求裡面有說到只要在30分鐘內找到3寶就好，那如果你測資給的mine.bin一開始就是超過三寶，是不是就代表其實也可以不用繼續找了，空跑等指令也可以，因為按照定義我已經找到3寶了？
感謝助教回答

**Comment by jerry73204** [comment]
這樣status指令不會過。

**Comment by timlee0119** [comment]
所以status指令的要求是，在30分鐘內每次輸入status都要顯示I'm working on不同的MD5嗎?
作業網站上只有寫：# each client's stdout. the hash may vary from time to time
"may"的語意感覺是"可以"、"可能"，不太像一定要吧
希望能請助教幫忙釐清一下空轉是哪裡不會過，如果是以上的情況的話，代表boss只要還沒quit，miner都要一直算嗎？

**Comment by jerry73204** [comment]
只要確保評測時，至少一次status有輸出即可，不然助教無法確認你有完成指令實作。
