### ISSUE TITLE
READmine.bin時的server I/O

### ISSUE THREAD

**Issue by tsunghan-wu** [SystemProgrammingatNTU/mp3-discussion#49]
read mine.bin的時候要handle這3個command嗎？
如果需要，
> status的話client要輸出空字串的hash嗎？
> dump的話是要dump一個空檔案對吧？
還是並不會有這個問題？
(也就是說保證先read完檔案，傳該大檔案的MD5_CTX給client後，client輸出BOSS is mindful! 才開始會有command？)

**Comment by tall15421542** [comment]
也有這個疑問+1
當檔案還沒讀完時，server可以即時回應沒問題，但是客戶端有一點疑問
我的理解如下
若檔案還沒讀完
（1）接收到status指令 server: printf("Best 0-treasure in 0 bytes\n"); client: (不知道請助教解答)
（2)  接收到dump指令 server: 輸出空擋 client: 無
（3)  接收到quit指令 server: 中斷讀檔，結束程式 client: printf("Boss is at rest\n");
以上是我的理解，請助教確認一下～

**Comment by jerry73204** [comment]
如果有上述情況
* status
client請不印字
* dump
server輸出空檔，client無關
* quit
中斷讀檔，server直接結束程式

待會補充到作業spec，感謝提醒。

**Comment by ghost** [comment]
> quit
> 中斷讀檔，server直接結束程式

之前不是說要等IO結束再退出嗎？

**Comment by jerry73204** [comment]
那是dump指令不能馬上結束，詳細說明已經補充到spec。
