### ISSUE TITLE
路徑問題

### ISSUE THREAD

**Issue by plsmaop** [SystemProgrammingatNTU/mp3-discussion#5]
不好意思問一個蠢問題，請問name pipes 跟 mine.bin是放在/client/tmp/下嗎？
還是說不用管，~/config.txt裡給的是什麼，就用什麼

如果照著網站上，會大概變成這個樣子
cd /path/to/repo/client
make
./miner Ada /tmp/ada_in /tmp/ada_out
此時，因為miner是在/client下執行，所以miner會在/client/tmp/下建立name pipe

然後
echo -n R06922148 > /tmp/mine.bin

cat > ~/config.txt <<<EOF
MINE: /tmp/initial.bin\n
MINER: /tmp/ada_in /tmp/ada_out\n
EOF\n

然後
cd /path/to/repo/server
make
./boss ~/config.txt

此時，因為boss是在/server下執行的，所以對於boss來說，mine.bin的位置是/server/tmp/initial.bin，這樣對嗎？

**Comment by jerry73204** [comment]
路徑位置請依照config.txt內容。

釐清一點，"/"字開頭的路徑是絕對路徑，/tmp/ada_in代表根目錄"/"下的目錄"tmp"下的檔案"ada_in"，而根目錄是最頂的路徑。

如果要代表當下位置下的server目錄，可以用相對路徑./server表示，其中"."指當下位置。

照如此解讀，上面寫的/client、/server應該是不正確用詞。只要照上述規則找檔即可。

實作上，直接把路徑丟給open()就好惹。

**Comment by plsmaop** [comment]
感謝，原來我搞錯了
