### ISSUE TITLE
用NONBLOCK 寫進 FIFO

### ISSUE THREAD

**Issue by drevil5678** [SystemProgrammingatNTU/mp3-discussion#51]
助教你好
我在處理dump的路徑是存在的FIFO的時候
用NONBLOCKING 檢查寫完了沒
但是每次write都write 0 byte而已
(有開另一個process cat那個FIFO)
請問有可能是什麼原因QQ

**Comment by jerry73204** [comment]
通常是對方已經close。（執行一次cat結束後會close一次）

**Comment by drevil5678** [comment]
test123

**Comment by drevil5678** [comment]
可是cat被卡住沒有執行完  不是代表他沒close那個FIFO嗎
