### ISSUE TITLE
Scoreboard is broken (treasure submitted between Dec 2 and Dec 6 are missing)

### ISSUE THREAD

**Issue by johnchen902** [SystemProgrammingatNTU/mp3-discussion#53]
As title.

This is a (cropped) screenshot from Dec 3 taken by @fsps60312: 
![Screenshot Dec 3](https://user-images.githubusercontent.com/5734324/33693731-6fa77e3a-db2f-11e7-9488-6547f2377e65.jpg)

This is a screenshot now (Dec 7):
![Screenshot Dec 7](https://user-images.githubusercontent.com/5734324/33693589-ada598e4-db2e-11e7-92b4-c3973f5f5b5d.png)

**Comment by jerry73204** [comment]
已經寄信說明原因了，如果名字不在上面的請重新上傳><
