### ISSUE TITLE
請問mine.bin會是絕對路徑嗎？

### ISSUE THREAD

**Issue by singyaowu** [SystemProgrammingatNTU/mp3-discussion#54]
如題，如果我叫boss把mine.bin的路徑傳給miner要他們開檔把字串append到mine.bin後面，直接傳config裡面mine.bin的位置miner會打得開嗎？

**Comment by jerry73204** [comment]
如果是相對路徑就不保證。

**Comment by singyaowu** [comment]
感謝助教，還有一個問題是關於MD5的，如果我用boss開mine然後傳MD5_CTX給miner，miner要MD5Update時傳給MD5Update的字串沒有限定長度，只要給字串跟長度就可以MD5Final出MD5吧？

**Comment by jerry73204** [comment]
final前你隨時update幾次多長都行，詳細使用方式請自己參考網路上的範例。

**Comment by singyaowu** [comment]
了解了 感謝助教
