### ISSUE TITLE
想問找MD5的過程

### ISSUE THREAD

**Issue by singyaowu** [SystemProgrammingatNTU/mp3-discussion#56]
看完HOWTO的分配工作方法後我還是不太懂要怎麼比較好的找treasure...
假設我分配\x00~\x3f給一個miner，那我是要\x00~\x3f都找過一遍，然後再從\x00\x00 ~ \x00\xff , \x01\x00 ~ \x01\xff, ...,  \x3f\x00 ~ \x3f\xff, 然後一直增加字元再重複這樣找嗎？因為這樣寫成程式好像光是計算下一步要換哪個字串就會花很久的時間，還是有沒有其他比較好的做法阿？
另外想問一下可以用C++嗎？

**Comment by jerry73204** [comment]
可以使用 C++。
MD5是被設計成很難被逆推、很難找到找到碰撞的演算法，暴力解是最直接的方式，你可以試試看在分配工作上做設計。（例如一個client負責湊2個byte或更多）
