### ISSUE TITLE
請問會連續dump 到同一個fifo裡面嗎？

### ISSUE THREAD

**Issue by nobel861017** [SystemProgrammingatNTU/mp3-discussion#57]
請問會連續dump 到同一個fifo裡面嗎？
如果會的話，變成我如果dump一次之後要dump第二次的話我需要先read他，但是如果助教在測的時候有read他我程式裡就不需要read他
所以問題變成是說會不會連續dump好幾次才去看dump出來的檔案內容正不正確
謝謝助教

**Comment by jerry73204** [comment]
請看舊推文。
