### ISSUE TITLE
請問連續 dump 到 Named pipe 的行為

### ISSUE THREAD

**Issue by jd3main** [SystemProgrammingatNTU/mp3-discussion#58]
根據 Issue #21 
> 只要保證程式quit之後，dump出來的資料是最後一次的就行

還有 Issue #19 
> 有可能，檔案如果存在請直接覆蓋。

那當連續 dump 到某個 named pipe 的時候
由於沒辦法清除或覆蓋之前 dump 出去 named pipe 的資訊
第二次 dump 沒辦法保證 dump 出去的內容前面沒有奇怪的東西

請問是否有方法可以處理 ?
又或者在評測時不會有重複 dump 到某個 named pipe 的情況
能不能提供 dump 到 named pipe 時的評測方式呢

**Comment by jerry73204** [comment]
有可能會重複dump到同個FIFO，寫到FIFO是為了評測dump指令是否responsive，我不會去看FIFO讀出來的內容。
至於dump目標是檔案的情況下請直接覆蓋。
