### ISSUE TITLE
FIFO讀寫 blocking問題

### ISSUE THREAD

**Issue by b03201003** [SystemProgrammingatNTU/mp3-discussion#59]
第一次寫關於fifo的程式
希望程式做到的功能是server/client 寫fifo的時候 會block住
等到server/client另一方 讀同一個fifo的時候 兩邊才會繼續跑
然後如果沒人寫訊息也希望讀fifo要block住

但現在一直卡在這些地方 連續卡很多天了
1.每次對fifo進行write的時候  訊息就直接寫出去了  
2.while(1) read 迴圈會一直跑但是完全沒讀到任何東西 
但我open明明完全沒有設定任何的O_NONBLOCK!?

不知道有沒有什麼可供參考的資料來源
覺得如果有這部分的範例code作業應該可以很快完成QAQ
但現在應該是要交不出來了...

**Comment by jerry73204** [comment]
1. 寫入後kernel buffer沒有滿的情況下，write會成功並回傳。
2. 這情況常發生在FIFO的寫入進程已經close()，導致你read()總是回傳0。

**Comment by b03201003** [comment]
關於第一點
我一直以為FIFO是要block住等待兩端讀寫搭上線
而不能只有單方面進行讀或寫的!?
原來是我誤解了嗎
那就不知道要怎麼解決了QAQ

第二點那個  
根據執行的結果
server進程應該還在進行中(因為可以輸入command
然後client也正在繼續等著讀訊息
或是還會有別的可能嗎

**Comment by jerry73204** [comment]
你理解沒錯，FIFO要兩個process打開之後才可以讀寫，不然總是被阻塞。
剛提到kernel buffer沒有滿的意思是兩邊已經打開為前提，寫入者write後kernel buffer沒有滿，即使讀取者不進行read()，write()會回傳。

第二個部分，有考慮到server在close ()了FIFO之後，client()也有close() 並重開？

**Comment by b03201003** [comment]
咦我應該都沒有把fifo關掉!?
close()只用來關了config file
除此之外應該沒有關任何東西!?

**Comment by jerry73204** [comment]
請用gdb去檢查看看是不是其他問題。
