### ISSUE TITLE
關於檔案位置問題

### ISSUE THREAD

**Issue by Nighteye841228** [SystemProgrammingatNTU/mp3-discussion#6]
想問一下
```
config.txt
mine: mine.bin
miner: miner_in miner_out
```
這些檔案的位置和pipe的名字我們都可以自訂嗎？
只要到時候open抓的到檔案就沒問題了？

**Comment by jerry73204** [comment]
可以自定名稱。助教評測時會使用自定的設定檔。

**Comment by Nighteye841228** [comment]
什麼叫做自訂的設定檔呢，
我們測試的時候config和pipe應該要放在什麼資料夾？
因為不確定到時候測試的路徑所以不知道到底該怎麼設定……

**Comment by jerry73204** [comment]
沒有硬性規定設定檔和pipe的名稱和位置，只要求你的程式能根據給定的路徑找到檔案。實作上把路徑直接丟給open()就可以了。

助教評測不會使用你上傳的設定檔，會另外寫一份專門評測用的。

**Comment by Nighteye841228** [comment]
OK，瞭解了

**Comment by nobel861017** [comment]
請問path的字串長度有限制嗎？

**Comment by jerry73204** [comment]
不超過PATH_MAX。
