### ISSUE TITLE
有沒有語法是保證fifo寫完一定會close之後才能被其他process使用

### ISSUE THREAD

**Issue by nobel861017** [SystemProgrammingatNTU/mp3-discussion#60]
Issue #58 

> 那當連續dump 到某個 named pipe 的時候
> 由於沒辦法清除或覆蓋之前 dump 出去 named pipe 的資訊  .....

我也有遇到一樣的問題
我覺得是因為我fifo還沒被關起來就被其他process寫入
請問有沒有語法是保證它寫完一定會close之後才能被其他process使用

**Comment by nobel861017** [comment]
我有試過了  加O_TRUNC無法解決問題

**Comment by jerry73204** [comment]
> 我覺得是因為我fifo還沒被關起來就被其他process寫入

作業的架構下，FIFO一次只會被server或者client其中一者寫入，這情況理應不會發生。請查詢看看是不是其他原因。

> 請問有沒有語法是保證它寫完一定會close之後才能被其他process使用

就我所知是沒有，但是你可以用lsof檢查你程式的open file
