### ISSUE TITLE
dump到FIFO的要求是?

### ISSUE THREAD

**Issue by b05902053** [SystemProgrammingatNTU/mp3-discussion#61]
我回去爬舊文很久
沒有找到相應的答案
所以再提一次問題  但是這次問的更具體些:
我先講一下我的理解
如果dump到一個不存在的檔案
就把它當作regular file來write

那如果dump到一個存在的regular file 就先把長度truncate到0 然後開始寫
而且測試資料應該有保證 這個檔案類型 只有可能是regular file或FIFO(應該不會是symbolic link?)

如果是regular file 這裡的要求應該就是檔案內容必須正確

但是如果是一個存在的FIFO會有個問題:
之前推文我看到的是助教會幫我們開一個fd open for read
讓我們open for write的時候不會block住
不過不一定會真的read下去(助教之前有回我說不一定)

然而FIFO本身是有一個kernel buffer
當助教dump 1GB的檔案進FIFO的時候

如果都不read, 因為檔案太大, FIFO的buffer一定會滿
到時候我們的write就會寫不進去
準確來說 如果這個write是blocking的它就會block住
如果是用non blocking的write那就會一直寫不進去(errno = EAGAIN)
即使用 select 也等不到可以寫的時候

所以我們沒辦法把1GB的內容全部寫進FIFO裡
除非助教幫我們read或者我們自己要幫自己read

說到這裡我的疑惑在於:
如果助教沒有幫我們read的時候  對於FIFO檔的dump 我們什麼情況下要自己read掉?
我想到三種可能的方式
1.自己開一個blocking的read 每write多少就read多少
2.用select判斷FIFO的kernel buffer是不是滿了, 如果滿了再自己read一些出來
3. 我們都不要自己read 就一直等一直等
等到助教幫我們read掉最後才write
如果一直等不到
那server收到quit指令程式就不會終止

請問這次的要求是?

**Comment by nobel861017** [comment]
真心希望不要短時間dump到同一個fifo多次:)))

**Comment by jerry73204** [comment]
開FIFO不讀用意是讓FIFO被寫滿，以測試你的使用者指令是否responsive。我是希望同學把FIFO視為單向通道，不需要去把資料讀出。
至於quit的問題，我最終會把資料讀出，這項測試不會和太多其他功能綜合檢測，請放心。

**Comment by nobel861017** [comment]
> 開FIFO不讀用意是讓FIFO被寫滿

那這樣還會去看dump的內容正不正確嗎

**Comment by b05902053** [comment]
了解!
那像是這種
dump a.fifo
status
dump b.fifo
dump c.txt
quit
我的程式會在a.fifo的buffer滿了之後一直處於等待的狀態
但是仍然能對status和quit做出反應
至於對c.txt的寫入
要到a.fifo和b.fifo寫完之後才會開始
這樣子按照順序的寫檔應該ok?

**Comment by jerry73204** [comment]
會檢查是否有輸出。

**Comment by jerry73204** [comment]
只要保證程式結束之後，dump的結果是正確的即可。

**Comment by nobel861017** [comment]
> 只要保證程式結束之後，dump的結果是正確的即可

dump的結果是指a.fifo b.fifo還是c.txt
抱歉問這麼細因為我真的有點怕

**Comment by jerry73204** [comment]
我會檢查regular file。

**Comment by y87526** [comment]
> 只要保證程式結束之後，dump的結果是正確的即可。

請問這裡的程式結束保證是用quit來正常結束嗎？

**Comment by jerry73204** [comment]
是的。
