### ISSUE TITLE
請問config是會換的嗎

### ISSUE THREAD

**Issue by peter9503** [SystemProgrammingatNTU/mp3-discussion#62]
如題，還是不同boss都用同一個？

**Comment by nobel861017** [comment]
config換了那quit之後重新啟動會出問題吧？

**Comment by b05902053** [comment]
我順便問一個問題:
quit之後助教會不會
在重啟server前  改動mine.bin的內容?
如果會的話   我的code目前不能handle

**Comment by jerry73204** [comment]
評測時有專用設定檔，會依據測試的需要去配置。
