### ISSUE TITLE
dump problem

### ISSUE THREAD

**Issue by michael0703** [SystemProgrammingatNTU/mp3-discussion#64]
請問助教:如果不實作dump這個指令,最多會影響到10分裡面的幾分?
我目前知道的會有實作指令的那一分會拿不到.
請問還有那些部分dump會影響呢?

**Comment by jerry73204** [comment]
"Server handles multiple I/O"這一項會扣分。

**Comment by michael0703** [comment]
請問是扣一分嗎？

**Comment by jerry73204** [comment]
至少一分。
