### ISSUE TITLE
關於quit的幾個問題

### ISSUE THREAD

**Issue by leo08260826** [SystemProgrammingatNTU/mp3-discussion#66]
1.quit有需要在限定時間內處理完嗎?
EX:quit在第30分鐘輸入，但是還未dump完(比如還需要15分鐘)，那這樣會判錯嗎?
2.程式一定用quit來結束嗎，會不會用ctrl+c之類的結束?
3.找到3寶的定義是要dump出來嗎，還是有在stdout出現md5即可?

**Comment by jerry73204** [comment]
1. 30分鐘是找到3寶、dump並quit的總計時間，不會拖延下指令。
2. 保證quit終止
3. 要dump確認，其雜湊必須和stdout輸出相同
