### ISSUE TITLE
關於quit的問題

### ISSUE THREAD

**Issue by chu0802** [SystemProgrammingatNTU/mp3-discussion#67]
請問助教
規則是，在dump的過程中，同時要能接收stdin的其他指令
那請問，在dump的過程中，如果接到quit的指令
而且，client傳來了新挖到的n-treasure

這時候server端要在stdout上印出n-treasure discovered!，同時assign新工作嗎
還是接到quit消息，就可以跟client說掰掰，專心等dump結束。

麻煩助教了~~~

**Comment by jerry73204** [comment]
只要保證程式遵守下列行爲，quit 之後找到新礦的處理方式可以自由實作。
* 如果 client 選擇印出 found n-treasure 時，server 必須同時在 stdout 印字。
* quit 結束後，dump 出來的資料是正確的。

講白一點...你的 client 可以選擇不要印字
