### ISSUE TITLE
請不要算我遲交

### ISSUE THREAD

**Issue by fsps60312** [SystemProgrammingatNTU/mp3-discussion#68]
我在12/7已經把作業寫完了，但聽說Spec在12/8有更動，那天凌晨4點我已經去搭飛機了啊QwQ
在緬甸比賽沒時間寫作業，網路也不太穩定，連git push都難成功，每天都沒睡飽、每個小時都很累，沒精力再管作業
到12/11晚上才回國，累到不行。但deadline 12/10已經過了
我今天終於有精神可以修code了，求求助教不要算我遲交><

**Comment by jerry73204** [comment]
可否寄信給助教你的出國競賽的證明（機票照片競賽資料都可）？會考慮讓你死線延期。
信箱 r06922148 (at) ntu (dot) edu (dot) tw

**Comment by fsps60312** [comment]
已寄
