### ISSUE TITLE
關於fifo

### ISSUE THREAD

**Issue by ghost** [SystemProgrammingatNTU/mp3-discussion#69]
助教好
請問server open到fifo之後可以把fifo unlink嗎？

**Comment by jerry73204** [comment]
建議不要，評測程式會檢查 fifo 檔案是存在。

**Comment by ghost** [comment]
那在server quit時unlink然後馬上重新創一個新的可以嗎？

**Comment by ghost** [comment]
會想這樣做是因為重複使用fifo的話
有時候client端收到server送的quit之後重新open了fifo
結果server在這個時候才執行到close
client讀到EOF就又要重open一次
處理起來有點冗冗的

想問有沒有什麼更好的解決方法
