### ISSUE TITLE
很基礎的md5問題

### ISSUE THREAD

**Issue by tall15421542** [SystemProgrammingatNTU/mp3-discussion#8]
請問一下如果我有一個字串str, 
md5(str, strlen(str), digest_buf)產生的md5是否是正確的，
還是md5的長度參數需要加上'\0', 所以是md5(str, strlen(str)+1, digest_buf)?

**Comment by jerry73204** [comment]
\0不納入md5雜湊計算，你可以拿md5sum指令驗證看看。

**Comment by MROS** [comment]
應該說，看你要做 hash 的字串有多長就給多長，而 '\0' 若作爲字串結尾標誌符則不計入字串本身。

**Comment by timlee0119** [comment]
那想請問一下，意思是在一個字串後面append一個"0x00"不會變動它的MD5囉?

**Comment by MROS** [comment]
會，如果你要計算的是 "0x010x00"，那你就將長度設爲 2 ，就會將 0x00 計算在內，重要的是妳究竟想要進行 hash 的字串長度有多長，而字串的內容隨意。

**Comment by jerry73204** [comment]
先釐清一點，MD5雜湊的輸入應該視為byte序列，\0結尾的字串只是眾多輸入的子集。對MD5來說，加\0只是輸入序列多一個byte，和字串應該\0結尾這件事沒有關係。

假定有個前提是你把MD5的輸入視為句子，通常"邏輯上"不會把\0當作句子的一部分，因此才建議輸入是字串可以不要零字。不過，MD5只是把輸入當byte序列，要不要加零字這點隨意。

建議試著用非""

**Comment by jerry73204** [comment]
上面按錯鍵提早送出= =，這裡補充一下
試著用操作數組序列的觀點想看看，實作上可以不用strlen, strcpy等字串相關函數就可以做到。
