### ISSUE TITLE
MINE path 長度限制 與example錯字問題

### ISSUE THREAD

**Issue by timlee0119** [SystemProgrammingatNTU/mp3-discussion#9]
如題，想請問config file 中MINE的檔案路徑的長度上限是多少?
另外還想請問：
mp3_example裡面boss.c的main funcition當中，
/* open the named pipes */那裏，
fd_ptr->input_fd與fd_ptr->output_fd都是open pipe_ptr->input_pipe耶，
是不是寫錯了？

**Comment by jerry73204** [comment]
已經修正了，感謝指正～

**Comment by timlee0119** [comment]
不好意思，還想請問config file 中MINE的檔案路徑的長度最長是多少？

**Comment by jerry73204** [comment]
不超過PATH_MAX。
